repository_location = ""
dataset_location = f"{repository_location}/Datasets"
results_location = f"{repository_location}/results"
website_sample_location = f"{results_location}/website_samples.pkl"
ground_truth_location = f"{results_location}/hand_aligned"
matching_location = f"{results_location}/matched"
