repository_location = ""
dataset_location = f"{repository_location}/Datasets"
website_sample_location = f"{repository_location}/results/website_samples.pkl"
ground_truth_location = f"{repository_location}/results/hand_aligned"
matching_location = f"{repository_location}/results/matched"
